Reorder production deployment docs
stackhpc/azimuth-config pull request #126
Opened 2024-03-20 09:46 UTC by JohnGarbutt

2024-03-20 09:58 UTC, mkjpryor requested changes
I think this is a better first effort. Just a couple of minor tweaks.

2024-03-20 09:58 UTC, mkjpryor commented on docs/best-practice.md
> +[environments](./environments.md)!
Maybe make this a tip?

```
!!! tip

    Remember to share as much configuration as possible between all your [environments](./environments.md)!
```

2024-03-20 09:58 UTC, mkjpryor commented on docs/best-practice.md
> +Also ensure you have
I think make these separate paragraphs for clarity.

2024-03-20 09:59 UTC, JohnGarbutt commented on docs/best-practice.md
> +[environments](./environments.md)!
feel free to add that, I have to run.

2024-03-21 11:14 UTC, mkjpryor requested changes
Just one minor rewording, I think.

2024-03-21 11:14 UTC, mkjpryor commented on docs/best-practice.md
> +matching TLS certificates and creating OpenStack application credentials.
This wording I find slightly clunky. What do you think of something like:

> Before proceeding with an [Azimuth deployment](./deployment/index.md),
> you should ensure that you can fulfil all the [prerequisites](./configuration/01-prerequisites.md).
>
> This includes verifying that the target cloud has the required features available, generating
> credentials and ensuring that the required DNS records and TLS certificates are available.

2024-03-21 11:24 UTC, mkjpryor approved these changes
LGTM

2024-03-21 11:24 UTC, merged