Package zip needed
stackhpc/azimuth-config pull request #132
Opened 2024-03-26 09:26 UTC by jjo93sa

Testing at Graphcore indicates the zip package is needed, otherwise the following error results:

```
TASK [stackhpc.terraform.install : Download Terraform binary] ******************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to find handler for \"/root/.ansible/tmp/ansible-tmp-1711384768.5950997-5388-98444872472118/tofu_1.6.1_linux_amd641a4f1kmx.zip\". Make sure the required command to extract the file is installed.
```

2024-03-27 12:20 UTC, mkjpryor requested changes

2024-03-27 12:20 UTC, mkjpryor commented on bin/ci-setup
> +fi
Move this before `run_apt update` above

2024-03-27 12:20 UTC, mkjpryor commented on bin/ci-setup
> +run_apt install -y -t 'o=LP-PPA-mozillateam' firefox
Then `firefox` can just be added to the list above I think? What does the `-t 'o=LP-PPA-mozillateam'` thing do?

2024-03-27 12:39 UTC, jjo93sa commented on bin/ci-setup
> +fi
Will do

2024-03-27 12:41 UTC, jjo93sa commented on bin/ci-setup
> +run_apt install -y -t 'o=LP-PPA-mozillateam' firefox
The extra flag tells `apt` to use the Mozilla PPA rather than the standard, which would install Firefox as a Snap (perhaps this is a workable solution?)

I'll need to get if that flag can be added to the previous list without impacting the other packages

2024-03-27 13:41 UTC, jjo93sa commented on bin/ci-setup
> +fi
Ah, I'd forgotten that the package `software-properties-common` is required to install the `add-apt-repository` command. Hence the order in the PR

2024-03-27 13:51 UTC, jjo93sa commented on bin/ci-setup
> +fi
I'll try the Snap version and see if it works with the tests

2024-03-27 13:58 UTC, jjo93sa commented on bin/ci-setup
> +fi
Nope, snap version isn't working... So it looks to me as though the code submitted in the PR is required as is?

2024-04-02 14:17 UTC, mkjpryor approved these changes
LGTM

2024-04-02 14:17 UTC, merged