Don't run CI on draft PRs
stackhpc/azimuth-config pull request #33
Opened 2023-06-05 09:29 UTC by sd109

2023-06-05 09:35 UTC, sd109 commented
Looks like this triggered CI twice because I originally opened it as a draft with a review request then changed it from draft to ready for review.

2023-06-05 09:59 UTC, sd109 commented
Would we rather just have CI triggered on 'ready for review' and not 'review requested' so that it doesn't get triggered twice?

2023-06-05 15:16 UTC, mkjpryor requested changes

2023-06-05 15:16 UTC, mkjpryor commented on .github/workflows/demo-deploy.yml
> +        # then running the seed-ssh script as normal.
Actually, you can specify it as an extra argument to `source ./bin/activate`, which is what the `ci-exec` script does, e.g.:

```
source ./bin/activate ci ci-<run-id>
```

2023-06-05 15:16 UTC, mkjpryor commented on .github/workflows/demo-deploy.yml
> +        # then running the seed-ssh script as normal.
And, actually, documented here in the GitLab context: https://stackhpc.github.io/azimuth-config/deployment/automation/#per-branch-dynamic-review-environments

2023-06-06 10:12 UTC, sd109 commented on .github/workflows/demo-deploy.yml
> +        # then running the seed-ssh script as normal.
Thanks, I'd forgotten about this

2023-06-09 16:38 UTC, mkjpryor submitted a review, later dismissed
LGTM

2023-06-09 16:40 UTC, mkjpryor approved these changes
LGTM

2023-06-09 16:43 UTC, merged