Add a specific mixin environment for doing CAPI mgmt clusters
stackhpc/azimuth-config pull request #37
Opened 2023-06-09 11:13 UTC by mkjpryor

2023-07-11 15:52 UTC, JohnGarbutt commented on environments/capi-mgmt/inventory/group_vars/all.yml
> +capi_cluster_kubernetes_version: "1.26.5"
Is this out of date now?

2023-07-11 15:53 UTC, JohnGarbutt requested changes
Can we add a README or docs we can reference from the StackHPC kayobe config? Maybe that is overkill.

2023-09-27 12:54 UTC, mkjpryor commented
> Can we add a README or docs we can reference from the StackHPC kayobe config? Maybe that is overkill.

Personally, I would rather we do the opposite, and keep the azimuth-config docs clean for Azimuth deployments.

2023-09-27 15:49 UTC, scrungus approved these changes
LGTM

2023-09-27 15:52 UTC, merged