Bump azops to pick up Zenith monitoring
stackhpc/azimuth-config pull request #43
Opened 2023-07-27 16:01 UTC by mkjpryor

2023-07-27 16:16 UTC, m-bull submitted a review, later dismissed

2023-07-27 16:33 UTC, m-bull requested changes
Please fix expected alerts in CI

2023-07-27 18:56 UTC, m-bull requested changes

2023-07-27 18:56 UTC, m-bull commented on .github/workflows/demo-deploy.yml
> +        if: ${{ always() }}
This seems like a situation where we shouldn't use `always()`:

>  Avoid using always for any task that could suffer from a critical failure.

https://docs.github.com/en/actions/learn-github-actions/expressions#always

2023-07-27 18:56 UTC, m-bull commented on .github/workflows/demo-deploy.yml
> +        if: ${{ always() }}
```suggestion
        if: ${{ !cancelled() }}
```

2023-07-27 19:58 UTC, mkjpryor commented on .github/workflows/demo-deploy.yml
> +        if: ${{ always() }}
The main objective here is not to leave resources hanging around in OpenStack in any case, including cancellation. 

In fact, because we use concurrency control on the PR, we definitely do need to be able to handle the cancellation case by removing resources.

2023-07-28 08:06 UTC, m-bull commented on .github/workflows/demo-deploy.yml
> +        if: ${{ always() }}
Good point - missed the concurrency stuff

2023-07-28 08:06 UTC, m-bull approved these changes

2023-07-28 08:12 UTC, merged