Update docs to reflect current best practice
stackhpc/azimuth-config pull request #48
Opened 2023-08-15 10:38 UTC by mkjpryor

2023-08-15 12:33 UTC, m-bull requested changes

2023-08-15 12:33 UTC, m-bull commented on docs/best-practice.md
> +the [Deployment method](http://localhost:8000/configuration/02-deployment-method/).
```suggestion
the [Deployment method](./configuration/02-deployment-method.md).
```

2023-08-15 12:33 UTC, m-bull commented on docs/configuration/01-prerequisites.md
> +Train and newer.
```suggestion
on Train release and newer.
```

2023-08-15 12:33 UTC, m-bull commented on docs/configuration/01-prerequisites.md
> +external networks.
```bash
openstack network set --tag portal-external ${external_network_name}
```

2023-08-15 12:33 UTC, m-bull commented on docs/configuration/03-kubernetes-config.md
> +capi_cluster_root_volume_type: nvme
```bash
openstack volume type list
```

2023-08-15 12:33 UTC, m-bull commented on docs/configuration/03-kubernetes-config.md
> +[OVN Octavia driver](https://docs.openstack.org/ovn-octavia-provider/latest/admin/driver.html)
```suggestion
[OVN Octavia provider](https://docs.openstack.org/ovn-octavia-provider/latest/admin/driver.html)
```

2023-08-15 12:33 UTC, m-bull commented on docs/configuration/03-kubernetes-config.md
> +capi_cluster_apiserver_loadbalancer_provider: ovn
```bash
openstack loadbalancer provider list
```

2023-08-15 12:33 UTC, m-bull commented on docs/configuration/10-kubernetes-clusters.md
> +to mitigate the [rate limiting](https://docs.docker.com/docker-hub/download-rate-limit/).
```suggestion
to mitigate [rate limiting](https://docs.docker.com/docker-hub/download-rate-limit/).
```

2023-08-15 12:33 UTC, m-bull commented on docs/configuration/10-kubernetes-clusters.md
> +```
```suggestion
```
```

2023-08-15 12:35 UTC, mkjpryor commented on docs/best-practice.md
> +  * One for all-in-one (AIO) deployments for validating changes, e.g. `azimuth-cicd`
The "an" doesn't really make sense here. Probably just "All-on-one..." I guess

2023-08-17 10:30 UTC, m-bull approved these changes
Nice

2023-08-17 10:35 UTC, merged

2023-08-17 10:36 UTC, bbezak commented
nice, btw, I couldn't find git-crypt for rocky9 in repo anywhere (not even in epel9). However binary from github works, but it needs to have compat-openssl11 installed:

`wget https://github.com/AGWA/git-crypt/releases/download/0.7.0/git-crypt-0.7.0-linux-x86_64
./git-crypt-0.7.0-linux-x86_64: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
sudo dnf install compat-openssl11.x86_64

sudo cp git-crypt-0.7.0-linux-x86_64 /usr/local/bin/git-crypt
sudo chmod 711 /usr/local/bin/git-crypt

git-crypt version
git-crypt 0.7.0`